<?php
$rss->add("http://lukasepple.de/blog/rss.php");
$rss->add("http://spda.vela.uberspace.de/?feed=rss2");
$rss->add("http://www.blumenkraft.eu/feed/");
$rss->add("http://dreamings.de/feed/");
$rss->add("http://dasdom.de/WordPress/feed/");
$rss->add("http://kadero.be/feed/");
$rss->add("http://www.knaeckez.de/feed/");
$rss->add("http://maxim.orion.uberspace.de/feed/");
$rss->add("http://www.indanett.de/feed");
$rss->add("http://feeds.feedburner.com/Openmedi");
$rss->add("http://www.lebsanft.org/?feed=rss2");
$rss->add("http://thoughts.schifferart.com/feed/");
$rss->add("https://www.sirtomate.de/feed");
$rss->add("http://www.denkfaden.de/rss.xml");
$rss->add("http://www.pro2koll.de/feed/");
$rss->add("http://www.vlachbild.de/feed/");
$rss->add("http://keinehosensonntag.de/author/xl/feed/");
$rss->add("http://www.taptoplay.de/rss");
$rss->add("http://www.zwentner.com/?feed=rss2");
$rss->add("http://woleonard.wordpress.com/feed/");
?>
